2020-07-09 07:43:54,246 ERROR: Exception on /reset_password_request [POST] [in /home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mark/github/projects/servers_and_webapps/microblog/application/auth/routes.py", line 58, in reset_password_request
    send_password_reset_email(user)
  File "/home/mark/github/projects/servers_and_webapps/microblog/application/auth/email.py", line 8, in send_password_reset_email
    sender=current_app.config['ADMINS'][0],
TypeError: 'NoneType' object is not subscriptable
2020-07-09 07:44:20,799 INFO: Microblog startup [in /home/mark/github/projects/servers_and_webapps/microblog/application/__init__.py:67]
2020-07-09 07:44:26,083 ERROR: Exception on /reset_password_request [POST] [in /home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mark/github/projects/servers_and_webapps/microblog/application/auth/routes.py", line 58, in reset_password_request
    send_password_reset_email(user)
  File "/home/mark/github/projects/servers_and_webapps/microblog/application/auth/email.py", line 7, in send_password_reset_email
    send_email('[Microblog] Reset Your Password',
  File "/home/mark/github/projects/servers_and_webapps/microblog/application/email.py", line 16, in send_email
    Thread(target=send_async_email, args=(current_app.get_current_object(), msg)).start()
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Flask' object has no attribute 'get_current_object'
2020-07-09 07:46:34,957 INFO: Microblog startup [in /home/mark/github/projects/servers_and_webapps/microblog/application/__init__.py:67]
2020-07-09 08:13:38,373 INFO: Microblog startup [in /home/mark/github/projects/servers_and_webapps/microblog/application/__init__.py:67]
2020-07-09 08:34:34,890 INFO: Microblog startup [in /home/mark/github/projects/servers_and_webapps/microblog/application/__init__.py:67]
2020-07-09 08:40:57,236 INFO: Microblog startup [in /home/mark/github/projects/servers_and_webapps/microblog/application/__init__.py:67]
2020-07-13 06:07:58,951 INFO: Microblog startup [in /home/mark/github/projects/servers_and_webapps/microblog/application/__init__.py:67]
2020-07-14 07:46:25,792 INFO: Microblog startup [in /home/mark/github/projects/servers_and_webapps/microblog/application/__init__.py:73]
2020-07-14 07:48:51,884 INFO: Microblog startup [in /home/mark/github/projects/servers_and_webapps/microblog/application/__init__.py:73]
2020-07-14 07:51:08,638 INFO: Microblog startup [in /home/mark/github/projects/servers_and_webapps/microblog/application/__init__.py:73]
2020-07-14 07:54:55,451 INFO: Microblog startup [in /home/mark/github/projects/servers_and_webapps/microblog/application/__init__.py:73]
2020-07-15 05:44:15,484 INFO: Microblog startup [in /home/mark/github/projects/servers_and_webapps/microblog/application/__init__.py:73]
2020-07-15 08:04:12,315 INFO: Microblog startup [in /home/mark/github/projects/servers_and_webapps/microblog/application/__init__.py:73]
2020-07-20 08:35:53,897 INFO: Microblog startup [in /home/mark/github/projects/servers_and_webapps/microblog/application/__init__.py:73]
2020-07-21 07:37:56,403 INFO: Microblog startup [in /home/mark/github/projects/servers_and_webapps/microblog/application/__init__.py:73]
2020-07-21 07:38:29,234 ERROR: Exception on /search [GET] [in /home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/mark/github/projects/servers_and_webapps/microblog/application/main/routes.py", line 67, in search
    return render_template('search.html', title='Search', posts=posts,
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: search.html
2020-07-21 07:39:03,206 INFO: Microblog startup [in /home/mark/github/projects/servers_and_webapps/microblog/application/__init__.py:73]
